# This workflow is largely based on
# https://github.com/salsify/ember-css-modules/blob/master/.github/workflows/ci.yml

name: CI

# These trigger patterns courtesy of https://github.com/broccolijs/broccoli/pull/436
on:
  pull_request:
  push:
    # filtering branches here prevents duplicate builds from pull_request and push
    branches:
      - main
      - 'v*'
    # always run CI for tags
    tags:
      - '*'

  # early issue detection: run CI weekly on Sundays
  schedule:
    - cron: '0 6 * * 0'

env:
  CI: true

jobs:
  test-locked-deps:
    name: Locked Deps
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn workspace ember-cached-decorator-polyfill lint
      - name: Browser Tests
        run: yarn workspace ember-cached-decorator-polyfill test:ember

  test-in-packages:
    name: Test as dependency in real packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Lint
        run: yarn lerna run --scope "@test-packages/*" lint
      - name: Browser Tests
        run: yarn lerna run --scope "@test-packages/*" test:ember

  test-old-dependencies:
    name: Oldest Supported Env
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 10
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Browser Tests
        run: yarn workspace ember-cached-decorator-polyfill test:ember

  test-try:
    name: Ember Try
    runs-on: ubuntu-latest
    needs: [test-locked-deps]
    strategy:
      matrix:
        scenario:
          - ember-3.13
          - ember-lts-3.16
          - ember-lts-3.20
          - ember-release
          - ember-beta
          - ember-canary
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Try Scenario
        run: yarn workspace ember-cached-decorator-polyfill ember try:one ${{ matrix.scenario }}
